version: '3'

services:
  api-gateway:
    image: docker.nexus.archi-lab.io/archilab/prox-api-gateway
    ports:
      - "8081:8081"
    restart: always
    networks:
      - ptb

networks:
  ptb:
    external: true
